clear; clc; close all;

% ========================================================================
% TASK 1B - HARDWARE / REAL-TIME ECG FREQUENCY DOMAIN ANALYSIS
%
% Use this after the ECG dashboard saves one of these files:
%   ECG_FFT_Window_*.csv
%   ECG_FFT_Window_*.mat
%
% Required outputs generated by this script:
% Output 4a : full magnitude spectrum FFT
% Output 5a : zoomed spectrum from 0-50 Hz
% Output 6a : annotated spectrum with P/T band, QRS band, and noise peaks
% Output 7a : comparison table, RR BPM vs frequency-domain BPM
% Output 8a : written commentary
% Output 9a : hardware/acquisition information table
%
% This version follows the same logical structure as the dataset Task 1B
% script, but it is adapted for real-time hardware ECG window files.
% ========================================================================

%% ----------------------- SETTINGS --------------------------------------
outputFolder = fullfile(pwd, 'Task1B_hardware_outputs');
if ~exist(outputFolder, 'dir')
    mkdir(outputFolder);
end

mainsHz   = 50;       % Pakistan mains frequency
fallbackFs = 250;     % Default dashboard sampling rate

fprintf('\n============================================================\n');
fprintf('TASK 1B - HARDWARE / REAL-TIME ECG FREQUENCY DOMAIN ANALYSIS\n');
fprintf('============================================================\n');

%% ----------------------- LOAD HARDWARE ECG WINDOW ----------------------
% Select the CSV/MAT file saved by the ECG dashboard. The dashboard usually
% saves a 20 s ECG segment for FFT as ECG_FFT_Window_*.csv or .mat.

[ecgRaw, Fs, meta] = load_hardware_ecg_window(fallbackFs);

ecgRaw = double(ecgRaw(:));
ecgRaw = ecgRaw(isfinite(ecgRaw));

if numel(ecgRaw) < round(2 * Fs)
    error('The selected ECG window is too short for FFT and R-peak analysis.');
end

N = numel(ecgRaw);
time = (0:N-1)' / Fs;
meta.durationSec = N / Fs;
meta.Fs = Fs;

fprintf('Loaded hardware ECG window: %s\n', meta.recordID);
fprintf('Sampling rate: %.2f Hz\n', Fs);
fprintf('Segment duration: %.2f seconds\n', meta.durationSec);
fprintf('Patient/subject: %s | Age: %s | Notes: %s\n', ...
    meta.patientName, meta.patientAge, meta.patientNotes);

%% ----------------------- FILTER / PRE-PROCESS --------------------------
% Same filtering logic as the dataset script: baseline correction, high-pass,
% low-pass, notch filtering, normalization, and polarity correction.

F = ecg_design_filters(Fs, mainsHz, 0.5, 40, 35);
[ecgClean, stages] = ecg_apply_classical_filters(ecgRaw, Fs, F); 

%% ----------------------- R-PEAK BPM + HRV ------------------------------
[rLocs, rAmps] = ecg_detect_rpeaks(ecgClean, Fs);
[bpmRR, rmssd, sdnn, rrMs] = ecg_bpm_hrv(rLocs, Fs);

fig1 = figure('Name','Hardware ECG with R-peaks', ...
    'Color','w', ...
    'Position',[80 80 1100 550]);

plot(time, ecgClean, 'LineWidth', 1.2);
hold on; grid on;

if ~isempty(rLocs)
    plot(time(rLocs), rAmps, 'rv', 'MarkerFaceColor','r');
end

xlabel('Time (s)');
ylabel('Normalized amplitude');
title(sprintf('Hardware ECG after preprocessing: %s', meta.recordID), ...
    'Interpreter','none');

if ~isempty(rLocs)
    legend('Clean ECG','Detected R-peaks');
else
    legend('Clean ECG');
end

save_figure(fig1, fullfile(outputFolder,'Output3a_hardware_Rpeaks_HR_HRV.png'));

%% ----------------------- FFT FEATURES ----------------------------------
featRaw   = ecg_fft_features(ecgRaw, Fs, mainsHz);
featClean = ecg_fft_features(ecgClean, Fs, mainsHz);

f   = featClean.f;
mag = featClean.mag;

bpmFreq = featClean.hrBpm;

if isnan(bpmRR) || isnan(bpmFreq)
    percentError = NaN;
else
    percentError = abs(bpmRR - bpmFreq) / max(abs(bpmRR), eps) * 100;
end

%% ----------------------- OUTPUT 4a: FULL FFT ---------------------------
fig2 = figure('Name','Output 4a Hardware FFT Magnitude Spectrum', ...
    'Color','w', ...
    'Position',[80 80 1100 600]);

plot(f, mag, 'LineWidth', 1.3);
grid on;
xlabel('Frequency (Hz)');
ylabel('|X(f)| Magnitude');
title('Output 4a: Hardware ECG Single-Sided FFT Magnitude Spectrum');
xlim([0 Fs/2]);

save_figure(fig2, fullfile(outputFolder,'Output4a_hardware_full_fft.png'));

%% ----------------------- OUTPUT 5a: 0-50 Hz FFT ------------------------
fig3 = figure('Name','Output 5a Hardware Zoomed FFT 0-50 Hz', ...
    'Color','w', ...
    'Position',[80 80 1100 600]);

keep50 = f <= min(50, Fs/2);
plot(f(keep50), mag(keep50), 'LineWidth', 1.4);
grid on;
xlabel('Frequency (Hz)');
ylabel('|X(f)| Magnitude');
title('Output 5a: Hardware ECG Zoomed FFT Spectrum, 0-50 Hz');
xlim([0 min(50, Fs/2)]);

save_figure(fig3, fullfile(outputFolder,'Output5a_hardware_zoom_0_50Hz.png'));

%% ----------------------- OUTPUT 6a: ANNOTATED FFT ----------------------
fig4 = figure('Name','Output 6a Hardware Annotated Spectrum', ...
    'Color','w', ...
    'Position',[80 80 1150 650]);

plot(f(keep50), mag(keep50), 'LineWidth', 1.4);
grid on; hold on;
xlabel('Frequency (Hz)');
ylabel('|X(f)| Magnitude');
title('Output 6a: Annotated Frequency Spectrum of Hardware ECG');
xlim([0 min(50, Fs/2)]);

add_vline_label(gca, 0.5,  'Baseline wander < 0.5 Hz', '--');
add_vline_label(gca, 10,   'P/T morphology approx. 0.5-10 Hz', '--');
add_vline_label(gca, 40,   'QRS high-frequency energy approx. 10-40 Hz', '--');

if mainsHz <= min(50, Fs/2)
    add_vline_label(gca, mainsHz, sprintf('%d Hz power-line region', mainsHz), ':');
end

ampRef = max(mag(keep50));
if ~isfinite(ampRef) || ampRef <= 0
    ampRef = 1;
end

if isfinite(featClean.hrPeakHz) && featClean.hrPeakHz <= min(50, Fs/2)
    plot(featClean.hrPeakHz, featClean.hrPeakMag, 'rv', ...
        'MarkerFaceColor','r', ...
        'MarkerSize',8);
    text(featClean.hrPeakHz, featClean.hrPeakMag + 0.05*ampRef, ...
        sprintf(' HR peak %.2f Hz = %.1f BPM', featClean.hrPeakHz, bpmFreq), ...
        'FontWeight','bold', ...
        'Color','r');
end

if isfinite(featClean.ptPeakHz) && featClean.ptPeakHz <= min(50, Fs/2)
    plot(featClean.ptPeakHz, featClean.ptPeakMag, 'bs', ...
        'MarkerFaceColor','c', ...
        'MarkerSize',7);
    text(featClean.ptPeakHz, featClean.ptPeakMag + 0.09*ampRef, ...
        sprintf(' P/T low-band peak %.2f Hz', featClean.ptPeakHz), ...
        'FontWeight','bold', ...
        'Color','b');
end

if isfinite(featClean.qrsPeakHz) && featClean.qrsPeakHz <= min(50, Fs/2)
    plot(featClean.qrsPeakHz, featClean.qrsPeakMag, 'ko', ...
        'MarkerFaceColor','y', ...
        'MarkerSize',7);
    text(featClean.qrsPeakHz, featClean.qrsPeakMag + 0.13*ampRef, ...
        sprintf(' QRS HF peak %.2f Hz', featClean.qrsPeakHz), ...
        'FontWeight','bold', ...
        'Color','k');
end

if isfinite(featClean.noisePeakHz) && featClean.noisePeakHz <= min(50, Fs/2)
    plot(featClean.noisePeakHz, featClean.noisePeakMag, 'md', ...
        'MarkerFaceColor','m', ...
        'MarkerSize',7);
    text(featClean.noisePeakHz, featClean.noisePeakMag + 0.17*ampRef, ...
        sprintf(' Noise peak %.2f Hz', featClean.noisePeakHz), ...
        'FontWeight','bold', ...
        'Color','m');
end

save_figure(fig4, fullfile(outputFolder,'Output6a_hardware_annotated_fft.png'));

%% ----------------------- OUTPUT 7a: COMPARISON TABLE -------------------
comparisonTable = table( ...
    {'RR intervals'; 'Frequency-domain FFT'}, ...
    {sprintf('Median RR interval from %d detected R-peaks', numel(rLocs)); ...
     sprintf('Dominant HR peak = %.3f Hz', featClean.hrPeakHz)}, ...
    {'HR = 60 / median(RR)'; 'HR = dominant frequency x 60'}, ...
    [bpmRR; bpmFreq], ...
    [NaN; featClean.hrPeakHz], ...
    [0; percentError], ...
    'VariableNames', { ...
    'Method', ...
    'Input_Used', ...
    'Formula', ...
    'Heart_Rate_BPM', ...
    'Frequency_Hz', ...
    'Difference_from_RR_percent'});

writetable(comparisonTable, fullfile(outputFolder,'Output7a_hardware_hr_comparison.csv'));

disp('Output 7a: Hardware heart-rate comparison table');
disp(comparisonTable);

fig5 = figure('Name','Output 7a Hardware Comparison Table', ...
    'Color','w', ...
    'Position',[120 120 1150 320]);

annotation(fig5,'textbox',[0.02 0.91 0.96 0.08], ...
    'String','Output 7a: HR Comparison, Time Domain vs Frequency Domain', ...
    'EdgeColor','none', ...
    'FontWeight','bold', ...
    'FontSize',13, ...
    'HorizontalAlignment','center');

uitable('Parent', fig5, ...
    'Data', safeCellForUitable(comparisonTable), ...
    'ColumnName', cellstr(comparisonTable.Properties.VariableNames), ...
    'Units', 'normalized', ...
    'Position', [0.02 0.12 0.96 0.72]);

save_figure(fig5, fullfile(outputFolder,'Output7a_hardware_hr_comparison_table.png'));

%% ----------------------- OUTPUT 8a: COMMENTARY -------------------------
commentary = generate_hardware_commentary(meta, featRaw, featClean, bpmRR, bpmFreq, percentError);

fid = fopen(fullfile(outputFolder,'Output8a_hardware_frequency_commentary.txt'), 'w');
fprintf(fid, '%s\n', commentary);
fclose(fid);

fprintf('\nOutput 8a commentary:\n%s\n', commentary);

%% ----------------------- OUTPUT 9a: HARDWARE INFO TABLE ----------------
infoTable = table( ...
    {char(meta.source)}, ...
    {char(meta.recordID)}, ...
    Fs, ...
    meta.durationSec, ...
    {char(meta.patientName)}, ...
    {char(meta.patientAge)}, ...
    {char(meta.patientNotes)}, ...
    {char(meta.signalType)}, ...
    {char(meta.localFile)}, ...
    'VariableNames', { ...
    'Source', ...
    'Record_ID_or_File', ...
    'Sampling_Rate_Hz', ...
    'Segment_Duration_s', ...
    'Patient_Name', ...
    'Age', ...
    'Gender_or_Notes', ...
    'Signal_Type', ...
    'Local_File'});

writetable(infoTable, fullfile(outputFolder,'Output9a_hardware_information_table.csv'));

disp('Output 9a: Hardware information table');
disp(infoTable);

fig6 = figure('Name','Output 9a Hardware Information', ...
    'Color','w', ...
    'Position',[100 100 1250 310]);

annotation(fig6,'textbox',[0.02 0.91 0.96 0.08], ...
    'String','Output 9a: Hardware / Real-Time ECG Information Table', ...
    'EdgeColor','none', ...
    'FontWeight','bold', ...
    'FontSize',13, ...
    'HorizontalAlignment','center');

uitable('Parent', fig6, ...
    'Data', safeCellForUitable(infoTable), ...
    'ColumnName', cellstr(infoTable.Properties.VariableNames), ...
    'Units', 'normalized', ...
    'Position', [0.02 0.10 0.96 0.78]);

save_figure(fig6, fullfile(outputFolder,'Output9a_hardware_information_table.png'));

fprintf('\nAll hardware Task 1B outputs saved in folder:\n%s\n', outputFolder);

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

function [x, Fs, meta] = load_hardware_ecg_window(defaultFs)
% Loads dashboard-saved hardware ECG FFT window from CSV or MAT.
% CSV supported formats:
%   one column: ECG values only
%   two columns: time and ECG signal
% MAT supported format from dashboard:
%   fftSegment, fftTime, Fs, patientName, patientAge, patientNotes

[fn, fp] = uigetfile({ ...
    'ECG_FFT_Window_*.mat;ECG_FFT_Window_*.csv;*.mat;*.csv;*.txt', ...
    'Hardware ECG FFT window (*.mat, *.csv, *.txt)'}, ...
    'Select saved hardware ECG FFT window');

if isequal(fn,0)
    error('No hardware ECG window selected.');
end

filePath = fullfile(fp, fn);
[~,~,ext] = fileparts(filePath);

Fs = defaultFs;
x = [];
patientName = 'User measured';
patientAge = 'User entered on dashboard/report';
patientNotes = 'Hardware ECG acquisition';

switch lower(ext)
    case '.mat'
        S = load(filePath);

        if isfield(S, 'fftSegment')
            x = S.fftSegment(:);
        else
            x = first_numeric_vector_from_struct(S);
        end

        if isempty(x)
            error('No ECG vector was found inside the selected MAT file.');
        end

        if isfield(S, 'Fs') && isnumeric(S.Fs) && isscalar(S.Fs) && isfinite(S.Fs) && S.Fs > 0
            Fs = double(S.Fs);
        elseif isfield(S, 'fftTime') && numel(S.fftTime) > 2
            t = double(S.fftTime(:));
            dt = median_omitnan_local(diff(t));
            if isfinite(dt) && dt > 0
                Fs = 1/dt;
            else
                Fs = ask_sampling_rate(defaultFs);
            end
        else
            Fs = ask_sampling_rate(defaultFs);
        end

        if isfield(S, 'patientName')
            patientName = value_to_char(S.patientName);
        end
        if isfield(S, 'patientAge')
            patientAge = value_to_char(S.patientAge);
        end
        if isfield(S, 'patientNotes')
            patientNotes = value_to_char(S.patientNotes);
        end

        % If MAT file did not contain patient info, let the user fill it.
        if strcmp(patientName, 'User measured') || strcmp(patientAge, 'User entered on dashboard/report')
            [patientName, patientAge, patientNotes] = prompt_patient_info(patientName, patientAge, patientNotes);
        end

    case {'.csv','.txt'}
        try
            M = readmatrix(filePath);
        catch
            M = csvread(filePath);
        end

        M = M(:, any(isfinite(M),1));
        if isempty(M)
            error('Selected CSV/TXT file contains no numeric ECG data.');
        end

        if size(M,2) >= 2
            t = M(:,1);
            x = M(:,2);
            dt = median_omitnan_local(diff(t));
            if isfinite(dt) && dt > 0
                Fs = 1/dt;
            else
                Fs = ask_sampling_rate(defaultFs);
            end
        else
            x = M(:,1);
            Fs = ask_sampling_rate(defaultFs);
        end

        [patientName, patientAge, patientNotes] = prompt_patient_info(patientName, patientAge, patientNotes);

    otherwise
        error('Unsupported file extension: %s', ext);
end

x = double(x(:));
x = x(isfinite(x));

meta = struct();
meta.source = 'Hardware ESP32 + AD8232';
meta.recordID = fn;
meta.localFile = filePath;
meta.patientName = patientName;
meta.patientAge = patientAge;
meta.patientNotes = patientNotes;
meta.signalType = 'Real-time hardware ECG FFT window';
meta.durationSec = numel(x) / Fs;
end

function Fs = ask_sampling_rate(defaultFs)
try
    answer = inputdlg({'Sampling frequency Fs in Hz:'}, ...
        'Sampling Frequency', [1 45], {num2str(defaultFs)});
    if isempty(answer)
        Fs = defaultFs;
    else
        Fs = str2double(answer{1});
        if ~isfinite(Fs) || Fs <= 0
            Fs = defaultFs;
        end
    end
catch
    Fs = input(sprintf('Enter sampling frequency Fs in Hz [default %.0f]: ', defaultFs));
    if isempty(Fs) || ~isfinite(Fs) || Fs <= 0
        Fs = defaultFs;
    end
end
end

function [patientName, patientAge, patientNotes] = prompt_patient_info(defaultName, defaultAge, defaultNotes)
try
    answer = inputdlg({'Patient/Subject name:', 'Age in years:', 'Gender/notes:'}, ...
        'Hardware ECG Patient Information', [1 45], ...
        {char(defaultName), char(defaultAge), char(defaultNotes)});

    if isempty(answer)
        patientName = char(defaultName);
        patientAge = char(defaultAge);
        patientNotes = char(defaultNotes);
    else
        patientName = strtrim(answer{1});
        patientAge = strtrim(answer{2});
        patientNotes = strtrim(answer{3});
    end
catch
    patientName = char(defaultName);
    patientAge = char(defaultAge);
    patientNotes = char(defaultNotes);
end

if isempty(patientName), patientName = 'User measured'; end
if isempty(patientAge), patientAge = 'User entered on dashboard/report'; end
if isempty(patientNotes), patientNotes = 'Hardware ECG acquisition'; end
end

function x = first_numeric_vector_from_struct(S)
names = fieldnames(S);
x = [];
for k = 1:numel(names)
    val = S.(names{k});
    if isnumeric(val) && isvector(val) && numel(val) > 10
        x = val(:);
        return;
    elseif isnumeric(val) && ismatrix(val) && ~isempty(val) && size(val,1) > 10
        x = val(:,1);
        return;
    end
end
end


function m = median_omitnan_local(x)
x = x(:);
x = x(isfinite(x));
if isempty(x)
    m = NaN;
else
    m = median(x);
end
end

function out = value_to_char(x)
if ischar(x)
    out = x;
elseif isnumeric(x)
    if isscalar(x)
        out = num2str(x);
    else
        out = mat2str(x);
    end
elseif isstring(x)
    out = char(x);
else
    try
        out = char(x);
    catch
        out = 'Unknown';
    end
end
end

function F = ecg_design_filters(Fs, mainsHz, hpCut, lpCut, notchQ)
% Designs high-pass, low-pass, and notch filters.

if hpCut <= 0
    hpCut = 0.5;
end
if lpCut >= Fs/2
    lpCut = 0.8 * (Fs/2);
end

[bHP, aHP] = butter(2, hpCut/(Fs/2), 'high');
[bLP, aLP] = butter(2, lpCut/(Fs/2), 'low');
[bN,  aN]  = local_notch_coeffs(mainsHz, Fs, notchQ);

F = struct();
F.bHP = bHP; F.aHP = aHP;
F.bLP = bLP; F.aLP = aLP;
F.bN  = bN;  F.aN  = aN;
F.hpCut = hpCut;
F.lpCut = lpCut;
F.mainsHz = mainsHz;
F.notchQ = notchQ;
end

function [clean, stages] = ecg_apply_classical_filters(raw, Fs, F)
% Baseline removal + HP + LP + notch + normalization.

x = double(raw(:));

% Remove slow median baseline first.
baseWin = max(5, round(0.8 * Fs));
if mod(baseWin,2) == 0
    baseWin = baseWin + 1;
end

if exist('movmedian','file') || exist('movmedian','builtin')
    baseline = movmedian(x, baseWin);
else
    baseline = moving_mean(x, baseWin);
end

x0 = x - baseline;
x1 = filtfilt(F.bHP, F.aHP, x0);
x2 = filtfilt(F.bLP, F.aLP, x1);
x3 = filtfilt(F.bN,  F.aN,  x2);

x3 = x3 - median(x3);
scale = prctile_local(abs(x3), 95);
if ~isfinite(scale) || scale < eps
    scale = max(abs(x3));
end
if ~isfinite(scale) || scale < eps
    scale = 1;
end

clean = x3 / scale;

% Auto polarity: make R-peaks upward.
pol = estimate_r_polarity(clean, Fs);
clean = pol * clean;

stages = struct();
stages.raw = x;
stages.baselineRemoved = x0;
stages.highPass = x1;
stages.lowPass = x2;
stages.notch = x3;
stages.clean = clean;
end

function y = moving_mean(x, win)
win = max(1, round(win));
if win <= 1
    y = x;
else
    kernel = ones(win,1) / win;
    y = conv(x, kernel, 'same');
end
end

function polarity = estimate_r_polarity(x, Fs)
x = x(:);
minDist = round(0.40 * Fs);

try
    [~, posLoc] = findpeaks(x,  'MinPeakDistance', minDist);
    [~, negLoc] = findpeaks(-x, 'MinPeakDistance', minDist);
catch
    posLoc = simple_peak_locs(x, minDist);
    negLoc = simple_peak_locs(-x, minDist);
end

if isempty(posLoc)
    posScore = 0;
else
    posVals = sort(x(posLoc), 'descend');
    posScore = mean(posVals(1:min(5,numel(posVals))));
end

if isempty(negLoc)
    negScore = 0;
else
    negVals = sort(-x(negLoc), 'descend');
    negScore = mean(negVals(1:min(5,numel(negVals))));
end

polarity = 1;
if negScore > posScore
    polarity = -1;
end
end

function [rLocs, rAmps] = ecg_detect_rpeaks(ecg, Fs)
x = double(ecg(:));
rLocs = [];
rAmps = [];

if numel(x) < round(2 * Fs)
    return;
end

p25 = prctile_local(x, 25);
p75 = prctile_local(x, 75);
p90 = prctile_local(x, 90);
medx = median(x);
iqrVal = max(p75 - p25, 0.05);

minPeakHeight   = max(medx + 1.1 * iqrVal, p90);
minPeakDistance = round(0.35 * Fs);
minProm         = max(0.30, 0.45 * iqrVal);

try
    [pks, locs] = findpeaks(x, ...
        'MinPeakHeight', minPeakHeight, ...
        'MinPeakDistance', minPeakDistance, ...
        'MinPeakProminence', minProm);
catch
    try
        [pks, locs] = findpeaks(x, ...
            'MinPeakHeight', minPeakHeight, ...
            'MinPeakDistance', minPeakDistance);
    catch
        locs = simple_peak_locs(x, minPeakDistance);
        pks = x(locs);
        keep = pks >= minPeakHeight;
        locs = locs(keep);
        pks = pks(keep);
    end
end

% Remove edge detections.
edge = round(0.20 * Fs);
keep = locs > edge & locs < (numel(x) - edge);
locs = locs(keep);
pks  = pks(keep);

% Keep physiological RR intervals.
if numel(locs) >= 3
    rr = diff(locs) / Fs;
    validPair = rr >= 0.35 & rr <= 1.60;
    keepLoc = [true; validPair(:)];
    locs = locs(keepLoc);
    pks  = pks(keepLoc);
end

rLocs = locs(:);
rAmps = pks(:);
end

function locs = simple_peak_locs(x, minDist)
x = x(:);
cand = find(x(2:end-1) > x(1:end-2) & x(2:end-1) >= x(3:end)) + 1;

if isempty(cand)
    locs = [];
    return;
end

[~, order] = sort(x(cand), 'descend');
cand = cand(order);

chosen = [];
for k = 1:numel(cand)
    if isempty(chosen) || all(abs(cand(k) - chosen) >= minDist)
        chosen(end+1,1) = cand(k); %#ok<AGROW>
    end
end

locs = sort(chosen);
end

function [bpm, rmssd, sdnn, rrMs] = ecg_bpm_hrv(rLocs, Fs)
bpm = NaN;
rmssd = NaN;
sdnn = NaN;
rrMs = [];

if numel(rLocs) < 2
    return;
end

rr = diff(rLocs(:)) / Fs;
rr = rr(rr >= 0.35 & rr <= 1.60);

if isempty(rr)
    return;
end

medRR = median(rr);
rr = rr(abs(rr - medRR) <= 0.25 * medRR);

if isempty(rr)
    return;
end

bpm = 60 / median(rr);
rrMs = rr * 1000;

if numel(rrMs) >= 3
    rmssd = sqrt(mean(diff(rrMs).^2));
    sdnn = std(rrMs);
end
end

function feat = ecg_fft_features(x, Fs, mainsHz)
x = double(x(:));
x = x - mean(x);

N = numel(x);

% Hann window without requiring hann().
if N > 1
    w = 0.5 - 0.5*cos(2*pi*(0:N-1)'/(N-1));
else
    w = ones(N,1);
end

xw = x .* w;
Y = fft(xw);

P2 = abs(Y) / sum(w);
P1 = P2(1:floor(N/2)+1);

if numel(P1) > 2
    P1(2:end-1) = 2 * P1(2:end-1);
end

f = Fs * (0:floor(N/2))' / N;
mag = P1(:);

% Frequency bands. The display peaks use non-overlapping masks so the
% heart-rate fundamental does not get reported again as P/T or QRS energy.
hrBand       = f >= 0.70 & f <= 2.50;     % 42-150 BPM
ptBand       = f >= 0.50 & f <= 10.00 & ~hrBand;
qrsBand      = f >= 10.00 & f <= 40.00;
baselineBand = f >= 0.00 & f < 0.50;
signalBand   = f >= 0.50 & f <= 40.00;
noiseBand    = (f >= 0.00 & f < 0.50) | (f > 40.00 & f <= min(Fs/2,100.00));
highNoiseBand = f > 40.00 & f <= min(Fs/2,100.00);
mainsBand     = f >= max(0, mainsHz-1.0) & f <= min(Fs/2, mainsHz+1.0);

[hrPeakHz, hrPeakMag]       = band_peak(f, mag, hrBand);
[ptPeakHz, ptPeakMag]       = band_peak(f, mag, ptBand);
[qrsPeakHz, qrsPeakMag]     = band_peak(f, mag, qrsBand);
[noisePeakHz, noisePeakMag] = band_peak(f, mag, highNoiseBand);
[mainsPeakHz, mainsPeakMag] = band_peak(f, mag, mainsBand);

signalPower   = band_power(f, mag, signalBand);
noisePower    = band_power(f, mag, noiseBand);
baselinePower = band_power(f, mag, baselineBand);
mainsPower    = band_power(f, mag, mainsBand);

snrDb = 10 * log10(signalPower / max(noisePower, eps));

feat = struct();
feat.f = f;
feat.mag = mag;
feat.hrPeakHz = hrPeakHz;
feat.hrPeakMag = hrPeakMag;
feat.hrBpm = hrPeakHz * 60;
feat.ptPeakHz = ptPeakHz;
feat.ptPeakMag = ptPeakMag;
feat.qrsPeakHz = qrsPeakHz;
feat.qrsPeakMag = qrsPeakMag;
feat.noisePeakHz = noisePeakHz;
feat.noisePeakMag = noisePeakMag;
feat.mainsPeakHz = mainsPeakHz;
feat.mainsPeakMag = mainsPeakMag;
feat.signalPower = signalPower;
feat.noisePower = noisePower;
feat.baselinePower = baselinePower;
feat.mainsPower = mainsPower;
feat.snrDb = snrDb;
feat.mainsHz = mainsHz;
end

function [pkHz, pkMag] = band_peak(f, mag, mask)
pkHz = NaN;
pkMag = NaN;

idx = find(mask & isfinite(mag));
if isempty(idx)
    return;
end

[pkMag, rel] = max(mag(idx));
pkHz = f(idx(rel));
end

function P = band_power(f, mag, mask)
idx = mask & isfinite(mag);
if nnz(idx) < 2
    P = 0;
    return;
end

% Approximate spectral power from magnitude squared.
P = trapz(f(idx), mag(idx).^2);
end

function [b, a] = local_notch_coeffs(f0, Fs, Q)
% Returns unity filter if requested notch is outside the valid range.
if f0 <= 0 || f0 >= Fs/2
    b = 1;
    a = 1;
    return;
end

w0 = 2*pi*f0/Fs;
alpha = sin(w0)/(2*Q);

b0 = 1;
b1 = -2*cos(w0);
b2 = 1;

a0 = 1 + alpha;
a1 = -2*cos(w0);
a2 = 1 - alpha;

b = [b0 b1 b2] / a0;
a = [1 a1/a0 a2/a0];
end

function p = prctile_local(x, pct)
x = sort(x(:));
x = x(isfinite(x));

if isempty(x)
    p = NaN;
    return;
end

pct = max(0, min(100, pct));
idx = 1 + (numel(x)-1) * pct / 100;

lo = floor(idx);
hi = ceil(idx);

if lo == hi
    p = x(lo);
else
    p = x(lo) + (idx-lo) * (x(hi)-x(lo));
end
end

function txt = generate_hardware_commentary(meta, featRaw, featClean, bpmRR, bpmFreq, percentError)
lines = cell(10,1);

lines{1} = sprintf('1. The ECG segment was acquired from %s and loaded from the saved file %s.', ...
    meta.source, meta.recordID);

lines{2} = sprintf('2. The hardware ECG window was sampled at approximately %.2f Hz for %.2f s, which provides the frequency resolution needed for the FFT plot.', ...
    meta.Fs, meta.durationSec);

lines{3} = sprintf('3. The dominant heart-rate frequency peak was %.3f Hz, corresponding to %.1f BPM.', ...
    featClean.hrPeakHz, bpmFreq);

lines{4} = sprintf('4. The time-domain R-R interval method gave %.1f BPM, so the percentage difference was %.2f%%.', ...
    bpmRR, percentError);

lines{5} = sprintf('5. The low-frequency region below 0.5 Hz represents baseline wander caused by motion, respiration, or electrode contact changes.');

lines{6} = sprintf('6. The P-wave and T-wave components are slower ECG components and are mainly expected in the 0.5-10 Hz region; after excluding the heart-rate fundamental, the measured low-band peak was %.2f Hz.', ...
    featClean.ptPeakHz);

lines{7} = sprintf('7. The QRS complex contains sharper transitions, so its higher-frequency energy was summarized in the 10-40 Hz band; the measured QRS high-frequency peak was %.2f Hz.', ...
    featClean.qrsPeakHz);

lines{8} = sprintf('8. The %.0f Hz mains region was checked to identify possible power-line interference from the acquisition setup.', ...
    featClean.mainsHz);

lines{9} = sprintf('9. The computed SNR estimate after filtering was %.2f dB, based on signal-band power versus noise-band power.', ...
    featClean.snrDb);

lines{10} = '10. Overall, agreement between RR-based BPM and FFT-based BPM supports the quality of the hardware ECG recording and peak detection.';

txt = sprintf('%s\n', lines{:});
end

function out = safeCellForUitable(T)
% Converts table/cell values so older MATLAB uitable can display them.
% Older uitable accepts only numeric, logical, or char values inside cells.

if istable(T)
    out = table2cell(T);
else
    out = T;
end

for r = 1:size(out,1)
    for c = 1:size(out,2)
        x = out{r,c};

        if ischar(x)
            out{r,c} = x;

        elseif isnumeric(x)
            if isempty(x)
                out{r,c} = '';
            elseif isscalar(x)
                out{r,c} = num2str(x);
            else
                out{r,c} = mat2str(x);
            end

        elseif islogical(x)
            if x
                out{r,c} = 'true';
            else
                out{r,c} = 'false';
            end

        elseif iscell(x)
            if isempty(x)
                out{r,c} = '';
            else
                y = x{1};
                if isnumeric(y)
                    out{r,c} = num2str(y);
                elseif ischar(y)
                    out{r,c} = y;
                else
                    try
                        out{r,c} = char(y);
                    catch
                        out{r,c} = '';
                    end
                end
            end

        else
            try
                out{r,c} = char(x);
            catch
                out{r,c} = '';
            end
        end
    end
end
end

function add_vline_label(ax, xValue, labelText, lineStyle)
% Compatibility replacement for xline().

yl = ylim(ax);

line(ax, [xValue xValue], yl, ...
    'LineStyle', lineStyle, ...
    'Color', [0.25 0.25 0.25], ...
    'LineWidth', 1.0);

text(ax, xValue, yl(2), [' ' labelText], ...
    'Rotation', 90, ...
    'VerticalAlignment','top', ...
    'HorizontalAlignment','left', ...
    'FontSize',9, ...
    'Color',[0.15 0.15 0.15]);
end

function save_figure(figHandle, filePath)
% Saves figure using exportgraphics if available; otherwise uses print.

try
    exportgraphics(figHandle, filePath, 'Resolution', 300);
catch
    print(figHandle, filePath, '-dpng', '-r300');
end
end
